// frontend/wshop-marsrover-react/src/components/LandingHUD.js
import './LandingHUD.scss';
import React, { useState } from 'react';

const LandingHUD = (props) => {

  const [landingState, setLandingState] = useState({
    x: props.rover.x,
    y: props.rover.y,
    orientation: props.rover.orientation
  });


  const handleInputChange = (event) => {
    setLandingState((prevState) => {
      return { ...prevState, [event.target.name]: event.target.value };
    });
  }

  const onLandClickHandler = () => {

    console.log('LandingHUD: onLandClickHandler called')
    // Pass data to parent
    props.land({
      startX: landingState.x,
      startY: landingState.y,
      startOrientation: landingState.orientation,
      x: landingState.x,
      y: landingState.y,
      orientation: landingState.orientation,
      hasLanded: true
    });
  }

  const invalidData = landingState.x == null || landingState.x == "" || landingState.y == "" || landingState.y == null ||
    (landingState.orientation !== "N" &&
      landingState.orientation !== "S" &&
      landingState.orientation !== "E" &&
      landingState.orientation !== "W");

  console.log('LandingHUD: rendered')

  return (
    <div>
      <div>
        <h4>Land rover<br />========== </h4>
        <div className="coords">
          <div className="input-group--column">
            <label htmlFor="LandingHUD-x">X</label>
            <input id="LandingHUD-x" type="number" name="x" min="0" max="99" value={landingState.x || ''} onChange={handleInputChange} />
          </div>
          <div className="input-group--column">
            <label htmlFor="LandingHUD-y">Y</label>
            <input id="LandingHUD-y" type="number" name="y" min="0" max="99" value={landingState.y || ''} onChange={handleInputChange} />
          </div>
        </div>

        <label htmlFor="LandingHUD-orientation">Direction</label>
        <select id="LandingHUD-orientation" name="orientation" value={landingState.orientation} onChange={handleInputChange}>
          <option></option>
          <option value="N">N</option>
          <option value="E">E</option>
          <option value="S">S</option>
          <option value="W">W</option>
        </select>

        <div className="input-group--row button-land-container">
          {
            (!props.rover.hasLanded) &&
            <button className="button-land"
              onClick={onLandClickHandler}
              disabled={invalidData}>
              Land
              </button>}
        </div>
      </div>
    </div >
  );
}

export default LandingHUD;

// frontend/wshop-marsrover-vue/src/components/LandingHUD.vue
<template>
  <div>
    <div>
      <h4>
        Land rover
        <br>==========
      </h4>
      <div class="coords">
        <div class="input-group--column">
          <label for="LandingHUD-x">X</label>
          <input id="LandingHUD-x" v-model.number="x" type="number" min="0" max="99">
        </div>
        <div class="input-group--column">
          <label for="LandingHUD-y">Y</label>
          <input id="LandingHUD-y" v-model.number="y" type="number" min="0" max="99">
        </div>
      </div>

      <label for="LandingHUD-orientation">Direction</label>
      <select id="LandingHUD-orientation" v-model="orientation">
        <option></option>
        <option value="N">N</option>
        <option value="E">E</option>
        <option value="S">S</option>
        <option value="W">W</option>
      </select>
      <!-- <input id="LandingHUD-orientation" v-model="orientation" size="1"> -->

      <div class="input-group--row button-land-container">
        <button
          class="button-land"
          @click="onLandClick()"
          v-if="!rover.hasLanded"
          :disabled="invalidData"
        >Land</button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "LandingHUD",
  props: {
    rover: Object
  },
  data: function() {
    return {
      x: this.rover.x,
      y: this.rover.y,
      orientation: this.rover.orientation
    };
  },
  methods: {
    onLandClick: function() {
      this.$emit("land", {
        startX: this.x,
        startY: this.y,
        startOrientation: this.orientation,
        x: this.x,
        y: this.y,
        orientation: this.orientation,
        hasLanded: true
      });
    }
  },
  computed: {
    invalidData: function() {
      return (
        this.x == null ||
        this.y == null ||
        // now that we're not using a text input, we could
        // just do orientation == null, but let's leave
        // this in case we decide to change it back.
        (this.orientation !== "N" &&
          this.orientation !== "S" &&
          this.orientation !== "E" &&
          this.orientation !== "W")
      );
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
@import "../styles/_variables.scss";
label {
  display: block;
}
input[type="number"] {
  width: 3em;
}

input[type="number"]::-webkit-inner-spin-button,
input[type="number"]::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

select {
  background: transparent;
  color: $monochrome;
  border: 1px solid $monochrome;
  height: 36px;
}

.button-land-container {
  text-align: right;
}

.coords {
  display: flex;
  margin-bottom: 20px;
  .input-group--column {
    margin-right: 20px;
  }
}

.input-group--row {
  margin-top: 20px;
}
</style>
