// frontend/wshop-marsrover-react/src/components/RoversUi.js
import './RoversUi.scss';
import React from 'react';
import LandingHUD from "./LandingHUD";
import MovementHUD from "./MovementHUD";
import TransitionGroup from 'react-transition-group/TransitionGroup';
import CSSTransition from 'react-transition-group/CSSTransition';

const RoversUi = (props) => {


  const activeRover = { ...props.rovers[props.activeRoverNum] };

  const updateRoverHandler = (rover) => {
    console.log('RoverUI::Update roverhandler called', rover);
    props.updateRover(rover);
  }

  const switchRoverHandler = (index) => {
    console.log('RoverUI::switchRoverHandler called', index);
    props.switchRover(index);
  }

  console.log('RoverUI:: render');

  return (
    <div>
      <div className="RoversUi">
        <h3>Select rover</h3>
        <ul>
          {
            props.rovers.map((rover, index) => {
              return (
                <li key={index} className={(props.activeRoverNum === index) ? "active" : ""}>
                  <button
                    onClick={switchRoverHandler.bind(null, index)}>
                    {index}
                  </button>
                </li>)
            })
          }
        </ul>

        <TransitionGroup component={null} name="expandable">
          {props.rovers.map((rover, index) => (
            (index === props.activeRoverNum && !activeRover.hasLanded) &&
            (<CSSTransition timeout={500} className="fade" key={index} >
              <LandingHUD
                rover={rover}
                key={index}
                land={updateRoverHandler}
              ></LandingHUD>
            </CSSTransition>)
          )
          )}
        </TransitionGroup>

        <TransitionGroup component={null} name="expandable">
          {props.rovers.map((rover, index) => (
            (index === props.activeRoverNum && rover.hasLanded) &&
            (<CSSTransition timeout={50000} className="fade" key={index} >
              <MovementHUD
                rover={rover}
                key={index}
                updateSequence={updateRoverHandler}
              ></MovementHUD>
            </CSSTransition>)
          )
          )}
        </TransitionGroup>
      </div >
    </div >
  )
};

export default RoversUi;

// frontend/wshop-marsrover-vue/src/components/RoversUI.vue
<template>
  <div class="RoversUI">
    <h3>Select rover</h3>
    <ul>
      <li
        v-for="(rover, index) in rovers"
        :key="index"
        :class="{ active: activeRoverNum === index }"
      >
        <button @click="$emit('switch-rover', index)">{{ index }}</button>
      </li>
    </ul>

    <transition-group name="expandable">
      <LandingHUD
        v-for="(rover, index) in rovers"
        :rover="rover"
        :key="index"
        @land="updateRover"
        v-show="index === activeRoverNum && !activeRover.hasLanded"
      ></LandingHUD>
    </transition-group>

    <transition-group name="expandable">
      <MovementHUD
        v-for="(rover, index) in rovers"
        :rover="rover"
        :key="index"
        v-show="index === activeRoverNum && rover.hasLanded"
        @update-sequence="updateRover"
      ></MovementHUD>
    </transition-group>
  </div>
</template>

<script>
import LandingHUD from "./LandingHUD.vue";
import MovementHUD from "./MovementHUD.vue";

export default {
  name: "RoversUI",
  components: { LandingHUD, MovementHUD },
  props: {
    rovers: Array,
    activeRoverNum: Number
  },
  computed: {
    activeRover: function() {
      return { ...this.rovers[this.activeRoverNum] };
    }
  },
  methods: {
    updateRover: function(props) {
      this.$emit("update-rover", props);
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
@import "../styles/_variables.scss";
.RoversUI {
  padding: 20px;
  border: 1px solid $monochrome-dark;
}
ul {
  list-style-type: none;
  padding: 0;
  li {
    display: inline-block;
    border: 1px solid $monochrome;

    &.active {
      border-bottom: none;
      button {
        color: $monochrome-active;
      }
    }
    button {
      border: none;
      background: none;
      padding: 10px;
    }
  }
}
</style>
