// frontend/wshop-marsrover-react/src/components/Tile.js

import './Tile.scss';
import React from 'react';
import Rover from "./Rover";

const Tile = (props) => {

  const rover = props.rovers.find(rover => rover.x === props.x && rover.y === props.y);
  const hasRover = rover != null;
  const hasCrater = props.craters.find(crater => crater.x === props.x && crater.y === props.y) != null;

  console.log('Tile:: rendered.');

  return (
    <div className={"tile"} style={{ width: props.width + '%' }} >
      <div className="inner" >
        {(hasCrater) && <div className="crater">O</div>}
        {(hasRover) && <Rover rover={rover}></Rover>}
      </div>
    </div>
  );
}

export default Tile;

// frontend/wshop-marsrover-vue/src/components/Tile.vue
<template>
  <div class="tile" :style="{ width: width + '%'}">
    <div class="inner">
      <div class="crater" v-if="hasCrater">O</div>
      <Rover v-if="hasRover" :rover="rover"></Rover>
    </div>
  </div>
</template>

<script>
import Rover from "./Rover";

export default {
  name: "Tile",
  components: {
    Rover
  },
  props: {
    width: Number,
    x: Number,
    y: Number,
    rovers: Array,
    craters: Array
  },
  computed: {
    rover: function() {
      return this.rovers.find(
        rover => rover.x === this.x && rover.y === this.y
      );
    },
    hasRover: function() {
      return this.rover != null;
    },
    hasCrater: function() {
      return (
        this.craters.find(
          crater => crater.x === this.x && crater.y === this.y
        ) != null
      );
    }
  }
};
</script>

<style scoped lang="scss">
@import "../styles/_variables.scss";
.tile {
  border: 1px solid $monochrome-dark;
  .inner {
    position: relative;
    padding-top: 100%;
    & > div {
      position: absolute;
      top: 0;
      left: 0;
    }
  }
  @media (max-width: 767px) {
    font-size: 9px;
  }
}

.crater {
  color: $obstacle-colour;
}
</style>
